try:
    num=int("hello")
except ValueError as e:
    print("There exist error:",e)